import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PuzzleBackground from "./PuzzleBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const COLORS = [
  "#FF6F61",
  "#FFD700",
  "#88B04B",
  "#009B77",
  "#92A8D1",
  "#6B5B95",
  "#F7CAC9",
  "#FFB347",
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          style={{
            width: "100vw",
            minHeight: 180,
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            position: "absolute",
            top: 0,
            left: 0,
            zIndex: 10,
            pointerEvents: "none",
          }}
        >
          <img
            src="/Title.png"
            alt="Título"
            style={{
              marginTop: 24,
              maxWidth: "90vw",
              height: "auto",
              pointerEvents: "auto",
              display: "block",
              marginLeft: "auto",
              marginRight: "auto",
            }}
          />
          <h1
            style={{
              marginTop: 12,
              fontSize: 32,
              fontWeight: 700,
              letterSpacing: 1,
              textAlign: "center",
              userSelect: "none",
              pointerEvents: "auto",
              display: "block",
              marginLeft: "auto",
              marginRight: "auto",
              background: "none",
              WebkitBackgroundClip: "unset",
              WebkitTextFillColor: "unset",
              backgroundClip: "unset",
            }}
          >
            Olá, eu sou o<br />
            <span style={{ display: "block", marginTop: 8 }}>
              {"SANTIAGO MAGALHÃES!".split("").map((char, idx) => (
                <span
                  key={idx}
                  style={{
                    color: COLORS[idx % COLORS.length],
                    fontSize: 36,
                    fontWeight: 900,
                    letterSpacing: 2,
                    textTransform: "uppercase",
                  }}
                >
                  {char === " " ? "\u00A0" : char}
                </span>
              ))}
            </span>
          </h1>
          <img
            src="/Santiago.jpeg"
            alt="Santiago Magalhães"
            style={{
              marginTop: 16,
              maxWidth: 340,
              width: "100%",
              borderRadius: 24,
              boxShadow: "0 4px 24px rgba(0,0,0,0.12)",
              display: "block",
              marginLeft: "auto",
              marginRight: "auto",
              pointerEvents: "auto",
            }}
          />
        </div>
        <div
          style={{
            position: "fixed",
            inset: 0,
            width: "100vw",
            height: "100vh",
            zIndex: -2,
            background: "#eaf6ff", // azul super claro
            pointerEvents: "none",
          }}
        />
        <PuzzleBackground />
        {children}
      </body>
    </html>
  );
}
